# The number maps
maps: 2

# The coordinates of each spawn
0_game_size: 8
0_plot_0: 185,5,155
0_plot_1: 185,5,112
0_plot_2: 143,5,112
0_plot_3: 143,5,155
0_plot_4: 101,5,112
0_plot_5: 60,5,112
0_plot_6: 60,5,70
0_plot_7: 101,5,70

1_game_size: 8
1_plot_0: 185,5,155
1_plot_1: 185,5,112
1_plot_2: 143,5,112
1_plot_3: 143,5,155
1_plot_4: 101,5,112
1_plot_5: 60,5,112
1_plot_6: 60,5,70
1_plot_7: 101,5,70


# Set to false if you're not me
database_enabled: false
proxy_enabled: false

# Settings for the database
database_address: 127.0.0.1
database_name: Cookie
database_user: Cookie
database_password: Cookie